### PR TITLE
Add suffix and ignore_case to stringmatch

### PR DESCRIPTION
**Pull request by npolshakova**
Used by: https://github.com/solo-io/gloo-mesh-enterprise/pull/570

### CODE REVIEW

**Review by Sodman — APPROVED** [review]
LGTM

**Comment by harveyxia** [comment]
We'll need to follow up with a PR to implement this for Istio translation to VirtualServices

**Review by Sodman — DISMISSED** [review]
Still LGTM 👍

**Review by Sodman — APPROVED** [review]

**Pull request merged**
