### PR TITLE
Better doc release process

### PR DESCRIPTION
**Pull request by ryantking**
Solves two issues:
- Remove the need for hardcoded versions.json file, use git tags to build the list (greatest patch for each minor version past a given minimum version, 0.7.x for now) such that once a commit to main or release happens, the doc site is immediately updated.
- Uses the local changelog folder instead of the GitHub release body to build the changelog to solve a race condition where the GH release body wasn't updated until after docs were published, which previously required a second commit to master.

BOT NOTES: 
resolves https://github.com/solo-io/gloo-mesh/issues/1182
resolves https://github.com/solo-io/gloo-mesh/issues/545

### CODE REVIEW

**Comment by kdorosh** [comment]
Food for thought: one thing I'll note as a positive of using today's behavior (github API as source of truth) is that we can make manual edits to releases that already went out.

For example, Gloo Edge has had releases such as v1.6.0-beta10 (see in [docs](https://docs.solo.io/gloo-edge/latest/reference/changelog/enterprise/) generated from GH API) that had regressions. We could easily update the release notes by hand and call attention to it up front.

To do this and properly call attention up front while using local changelog as source of truth, may require some work in our changelog parsing utils and thus also an update to our changelog-bot

**Comment by joekelley** [comment]
Can you share a screenshot of how the unreleased section of the changelog will render?

**Comment by ryantking** [comment]
@joekelley It just shows the unreleaed versions:

main branch changelog

**Comment by ryantking** [comment]
After going over this in more detail and some of the implications originally not seen, we are opting to close this for now and use the original GitHub release API style of changelog generation. We are keeping this branch around as a reference for when we revisit changelog generation at a later date.

**Pull request closed without merging**
